-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 21:34:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- ------------------------------boughtfrom-----------------------
-- -----------------------------------------------------
-- Schema cs363chw2_f2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs363chw2_f2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs363chw2_f2018` DEFAULT CHARACTER SET utf8 ;
USE `cs363chw2_f2018` ;

-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`ingredients` (
  `itemid` INT(11) NOT NULL,
  `desc` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`itemid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`employees` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`employees` (
  `eid` INT(11) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `firstname` VARCHAR(30) NULL DEFAULT NULL,
  `lastname` VARCHAR(30) NULL DEFAULT NULL,
  `phone` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`eid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`hourly_workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`hourly_workers` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`hourly_workers` (
  `hWage` INT(11) NULL DEFAULT NULL,
  `hours` INT(4) NULL DEFAULT NULL,
  `specialty` VARCHAR(50) NULL DEFAULT NULL,
  `employees_eid` INT(11) NOT NULL,
  INDEX `fk_hourly_workers_employees1_idx` (`employees_eid` ASC) VISIBLE,
  PRIMARY KEY (`employees_eid`),
  CONSTRAINT `fk_hourly_workers_employees1`
    FOREIGN KEY (`employees_eid`)
    REFERENCES `cs363chw2_f2018`.`employees` (`eid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`products` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`products` (
  `iid` INT(11) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `qtyleft` INT(20) NULL DEFAULT NULL,
  `price` INT(8) NULL DEFAULT NULL,
  `hourly_workers_employees_eid` INT(11) NOT NULL,
  PRIMARY KEY (`iid`),
  INDEX `fk_products_hourly_workers1_idx` (`hourly_workers_employees_eid` ASC) VISIBLE,
  CONSTRAINT `fk_products_hourly_workers1`
    FOREIGN KEY (`hourly_workers_employees_eid`)
    REFERENCES `cs363chw2_f2018`.`hourly_workers` (`employees_eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`suppliers` (
  `sid` INT(11) NOT NULL,
  `sname` VARCHAR(30) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`sid`)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`boughtfrom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`boughtfrom` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`boughtfrom` (
  `qty` INT(11) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `DoP` VARCHAR(45) NULL DEFAULT NULL,
  `products_iid` INT(11) NOT NULL,
  `suppliers_sid` INT(11) NOT NULL,
  `ingredients_itemid` INT(11) NOT NULL,
  PRIMARY KEY (`products_iid`),
  INDEX `fk_boughtFrom_products1_idx` (`products_iid` ASC) VISIBLE,
  INDEX `fk_boughtFrom_suppliers1_idx` (`suppliers_sid` ASC) VISIBLE,
  INDEX `fk_boughtFrom_ingredients1_idx` (`ingredients_itemid` ASC) VISIBLE,
  CONSTRAINT `fk_boughtFrom_ingredients1`
    FOREIGN KEY (`ingredients_itemid`)
    REFERENCES `cs363chw2_f2018`.`ingredients` (`itemid`),
  CONSTRAINT `fk_boughtFrom_products1`
    FOREIGN KEY (`products_iid`)
    REFERENCES `cs363chw2_f2018`.`products` (`iid`),
  CONSTRAINT `fk_boughtFrom_suppliers1`
    FOREIGN KEY (`suppliers_sid`)
    REFERENCES `cs363chw2_f2018`.`suppliers` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`parts` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`parts` (
  `pid` INT(11) NOT NULL,
  `pname` VARCHAR(30) NULL DEFAULT NULL,
  `color` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`catalog` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`catalog` (
  `sid` INT(11) NOT NULL,
  `pid` INT(11) NOT NULL,
  `cost` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`sid`, `pid`),
  INDEX `pid_idx` (`pid` ASC) VISIBLE,
  CONSTRAINT `pid`
    FOREIGN KEY (`pid`)
    REFERENCES `cs363chw2_f2018`.`parts` (`pid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `cs363chw2_f2018`.`suppliers` (`sid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`customers` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`customers` (
  `cid` INT(11) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `firstname` VARCHAR(30) NULL DEFAULT NULL,
  `lastname` VARCHAR(30) NULL DEFAULT NULL,
  `phone` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`fulltime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`fulltime` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`fulltime` (
  `salary` INT(8) NOT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `employees_eid` INT(11) NOT NULL,
  INDEX `fk_fulltime_employees1_idx` (`employees_eid` ASC) VISIBLE,
  PRIMARY KEY (`employees_eid`),
  CONSTRAINT `fk_fulltime_employees1`
    FOREIGN KEY (`employees_eid`)
    REFERENCES `cs363chw2_f2018`.`employees` (`eid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`managers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`managers` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`managers` (
  `maxcapacity` INT(8) DEFAULT NULL,
  `salary` INT(8) DEFAULT NULL,
  `employees_eid` INT(11) NOT NULL,
  INDEX `fk_managers_employees1_idx` (`employees_eid` ASC) VISIBLE,
  PRIMARY KEY (`employees_eid`),
  CONSTRAINT `fk_managers_employees1`
    FOREIGN KEY (`employees_eid`)
    REFERENCES `cs363chw2_f2018`.`employees` (`eid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`producttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`producttype` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`producttype` (
  `typename` VARCHAR(50) NOT NULL,
  `products_iid` INT(11) NOT NULL,
  PRIMARY KEY (`typename`, `products_iid`),
  INDEX `fk_producttype_products1_idx` (`products_iid` ASC) VISIBLE,
  CONSTRAINT `fk_producttype_products1`
    FOREIGN KEY (`products_iid`)
    REFERENCES `cs363chw2_f2018`.`products` (`iid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cs363chw2_f2018`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs363chw2_f2018`.`purchase` ;

CREATE TABLE IF NOT EXISTS `cs363chw2_f2018`.`purchase` (
  `products_iid` INT(11) NOT NULL,
  `customers_cid` INT(11) NOT NULL,
  `purchaseQty` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`products_iid`, `customers_cid`),
  INDEX `fk_products_has_customers_customers1_idx` (`customers_cid` ASC) VISIBLE,
  INDEX `fk_products_has_customers_products1_idx` (`products_iid` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_customers_customers1`
    FOREIGN KEY (`customers_cid`)
    REFERENCES `cs363chw2_f2018`.`customers` (`cid`),
  CONSTRAINT `fk_products_has_customers_products1`
    FOREIGN KEY (`products_iid`)
    REFERENCES `cs363chw2_f2018`.`products` (`iid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
